config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'pages#home'

  get 'table', to: 'pages#table'

  resources :matches, only: [] do
    resources :predictions, except: :destroy
  end

end

app/models/club.rb
class Club < ActiveRecord::Base
  validates :name, presence: true
end

app/models/fixture_scraper.rb
require 'open-uri'

class FixtureScraper
  class << self
    def update_fixtures
      scraped_fixtures = scrape

      Match.upcoming.each do |upcoming_match|
        matching_fixtures_count = scraped_fixtures.count { |scraped_fixture|
          scraped_fixture == {
            kick_off: upcoming_match.kick_off,
            home_team: upcoming_match.home_team,
            away_team: upcoming_match.away_team
          }
        }
        upcoming_match.destroy if matching_fixtures_count == 0
      end

      scraped_fixtures.each do |scraped_fixture|
        Match.where(scraped_fixture).count > 0 || Match.create(scraped_fixture)
      end
    end

    def scrape
      page = Nokogiri::HTML(open('http://www.bbc.co.uk/sport/football/teams/tottenham-hotspur/fixtures'))
      page.css('#fixtures-data .table-stats tbody .preview').map do |row|
        {
          kick_off: parse_kick_off("#{row.css('.match-date').text} #{row.css('.kickoff').text}"),
          home_team: find_or_create_club(row.css('.match-details.teams .team-home.teams').text.strip),
          away_team: find_or_create_club(row.css('.match-details.teams .team-away.teams').text.strip)
        }
      end
    end

    def parse_kick_off kick_off_string
      parsed_time = Time.zone.parse kick_off_string
      parsed_time < Time.zone.now ? parsed_time + 1.year : parsed_time
    end

    def find_or_create_club team_name
      club_found = Club.find_by(name: team_name)
      club_found || Club.create(name: team_name)
    end
  end
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :home_team, class_name: 'Club'
  belongs_to :away_team, class_name: 'Club'
  has_many :predictions

  validates :home_team, presence: true
  validates :away_team, presence: true

  scope :upcoming, -> { where('kick_off > ?', Time.now - 3.hours).order(:kick_off) }
  scope :pending_score_update, -> { where('kick_off < ? AND (home_team_goals IS NULL OR away_team_goals IS NULL)', Time.now - 3.hours).order(:kick_off) }

  include ArrayStats

  def next_match?
    Match.upcoming.first.id == id
  end

  def result? home_goals = home_team_goals, away_goals = away_team_goals
    if home_goals == away_goals
      :draw
    elsif win? home_goals, away_goals
      :win
    else
      :loss
    end
  end

  def update_score home_goals, away_goals
    self.update home_team_goals: home_goals, away_team_goals: away_goals

    predictions.each do |prediction|
      prediction.update_points!
    end
  end

  def has_started?
    kick_off < Time.now
  end

  def average_prediction
    [
      median(predictions.pluck(:home_team_goals)).round,
      median(predictions.pluck(:away_team_goals)).round
    ]
  end

  private

  def win? home_goals, away_goals
    (home? && home_goals > away_goals) || (!home? && away_goals > home_goals)
  end

  def home?
    home_team.name == 'Tottenham Hotspur'
  end
end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
  belongs_to :match
  belongs_to :user

  validates :match, presence: true
  validates :home_team_goals, presence: true
  validates :away_team_goals, presence: true
  validates :home_team_goals, numericality: { greater_than_or_equal_to: 0 }
  validates :away_team_goals, numericality: { greater_than_or_equal_to: 0 }
  validates :match_id, uniqueness: { scope: [:user_id] }

  def result?
    match.result? home_team_goals, away_team_goals
  end

  def update_points!
    if correct_score?
      self.update points: 3
    elsif correct_result?
      self.update points: 1
    else
      self.update points: 0
    end
  end

  private

  def correct_score?
    if home_team_goals == match.home_team_goals && away_team_goals == match.away_team_goals
      true
    else
      false
    end
  end

  def correct_result?
    if result? == match.result?
      true
    else
      false
    end
  end
end

app/models/result_scraper.rb
require 'open-uri'

class ResultScraper
  class << self
    def update_results
      scraped_results = scrape

      Match.pending_score_update.each do |match|
        matching_results = scraped_results.select do |result|
          match.kick_off.to_date === result[:match_date] &&
          match.home_team_id == result[:home_team].id &&
          match.away_team_id == result[:away_team].id
        end

        next if matching_results.count == 0

        match.update_score(
          matching_results.first[:home_team_goals],
          matching_results.first[:away_team_goals]
        )
      end
    end

    def scrape
      page = Nokogiri::HTML(open('http://www.bbc.co.uk/sport/football/teams/tottenham-hotspur/results'))
      page.css('#results-data .table-stats tbody tr.report').map do |row|
        score = row.css('.match-details.teams .score').text.strip
        goals = score.split('-').map &:to_i

        {
          match_date: parse_kick_off(row.css('.match-date').text),
          home_team: find_or_create_club(row.css('.match-details.teams .team-home.teams').text.strip),
          away_team: find_or_create_club(row.css('.match-details.teams .team-away.teams').text.strip),
          home_team_goals: goals[0],
          away_team_goals: goals[1]
        }
      end
    end

    def parse_kick_off kick_off_string
      parsed_time = Date.parse kick_off_string
      parsed_time > Date.today ? parsed_time - 1.year : parsed_time
    end

    def find_or_create_club team_name
      club_found = Club.find_by(name: team_name)
      club_found || Club.create(name: team_name)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :predictions

  validates :username, presence: true
  validates :username, uniqueness: true

  class << self
    def users_ordered_by_points
      self.includes(:predictions).to_a.sort do |user_a, user_b|
        user_b.points <=> user_a.points
      end
    end
  end

  def points
    predictions.map(&:points).sum
  end

  def prediction_for match
    match.predictions.find_by user: self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    permitted_params = [
      :username,
    ]
    devise_parameter_sanitizer.for(:sign_up) << permitted_params
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @matches = Match.upcoming.first(5)
  end

  def table
    @users = User.users_ordered_by_points.each_with_index
  end
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_if_match_has_started
  before_action :find_prediction, only: [:edit, :update]

  def new
    @prediction = Prediction.new match_id: params[:match_id]
  end

  def create
    @prediction = Prediction.new prediction_form_fields.merge(user: current_user)

    if @prediction.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    if @prediction.user != current_user
      redirect_to root_path
    end
  end

  def update
    if @prediction.update prediction_form_fields
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def check_if_match_has_started
    if Match.find(params[:match_id]).has_started?
      flash[:danger] = 'This match has started.'
      redirect_to root_path
    end
  end

  def find_prediction
    @prediction = Prediction.find params[:id]
  end

  def prediction_form_fields
    params.require(:prediction).permit(
      :home_team_goals,
      :away_team_goals
    ).merge(user: current_user, match_id: params[:match_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def score home_goals, away_goals
    if home_goals == away_goals
      "#{home_goals}-#{away_goals}"
    else
      goals = [home_goals, away_goals]
      "#{goals.max}-#{goals.min}"
    end
  end
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key} flash-messages"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

:javascript
  setTimeout(function () {
    $('.flash-messages').fadeOut();
  }, 2000);

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %meta{property: "og:image", content: image_url('logo.png')}/
    %title Coysnews
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/flash_messages'
    %header.navbar.navbar-default.navbar-static-top
      %nav.container{:role => "navigation"}
        .navbar-header
          = link_to 'COYS NEWS', root_path, {class: 'navbar-brand'}
          %button.navbar-toggle.collapsed{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
        %ul.nav.navbar-nav.navbar-right.collapse.navbar-collapse
          / %li.dropdown
          /   %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "/about"}
          /     Articles
          /     %span.caret
          /   %ul.dropdown-menu{:role => "menu"}
          /     %li
          /       %a{:href => "#"} Some Articles
          /     %li
          /       %a{:href => "#"} Some more articles
          /     %li.divider
          /     %li
          /       %a{:href => "#"} Even more articles
          %li
            = link_to 'Prediction League Table', table_path

          - if !current_user
            %li
              = link_to 'Sign up', new_user_registration_path
          %li
            - if current_user
              = link_to 'Sign out', destroy_user_session_path, method: 'delete'
            - else
              = link_to 'Sign in', new_user_session_path
    .container
      = yield

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-42957746-1', 'auto');
      ga('send', 'pageview');

app/views/matches/_match.html.haml
- if current_user
  - prediction = current_user.prediction_for match
  - if match.has_started?
    - link = '#'
  - else
    - link = prediction ? edit_match_prediction_path(match, prediction) : new_match_prediction_path(match)
%a.list-group-item.text-center{href: link, class: match.next_match? ? 'active large' : ''}
  %p.list-group-item-text
    Kick off:
    = match.decorate.kick_off_date_and_time
  %h4.list-group-item-heading
    = "#{match.home_team.name} V #{match.away_team.name}"
  %p.list-group-item-text
    - if prediction
      = prediction.decorate.summary

app/views/pages/home.html.haml
.jumbotron
  %h1 Prediction League
  %p 3 points for the correct score
  %p 1 point for the correct result
  %a{class: 'btn btn-primary btn-lg', href: table_path, role: 'button'}
    View table
.list-group
  = render @matches

app/views/pages/table.html.haml
%table.table.table-striped
  %th
    Position
  %th
    User
  %th
    Points
  - @users.each do |user, index|
    %tr{class: user == current_user ? 'highlight' : ''}
      %td
        = index + 1
      %td
        = user.username
      %td
        = user.points

app/views/predictions/_form_fields.html.haml
= f.input :home_team_goals, label: f.object.match.home_team.name
= f.input :away_team_goals, label: f.object.match.away_team.name

app/views/predictions/edit.html.haml
.col-md-offset-3.col-md-6
  = simple_form_for(@prediction, url: match_prediction_path(@prediction.match, @prediction), method: 'patch', html: { class: 'form-horizontal' }) do |f|
    = render partial: 'form_fields', locals: {f: f}
    = f.button :submit

app/views/predictions/new.html.haml
.col-md-offset-3.col-md-6
  = simple_form_for(@prediction, url: match_predictions_path, method: 'post', html: { class: 'form-horizontal' }) do |f|
    = render partial: 'form_fields', locals: {f: f}
    = f.button :submit